
export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"
export const USER_LOGOUT = "USER_LOGOUT";


export const FETCH_INVENTORY_SUCCESS = 'FETCH_INVENTORY_SUCCESS';
export const FETCH_INVENTORY_FAILURE = 'FETCH_INVENTORY_FAILURE';

export const FETCH_DEALER_INVENTORY_SUCCESS = 'FETCH_DEALER_INVENTORY_SUCCESS';
export const FETCH_DEALER_INVENTORY_FAILURE = 'FETCH_DEALER_INVENTORY_FAILURE';

export const CREATE_INVENTORY_SUCCESS = 'CREATE_INVENTORY_SUCCESS';
export const CREATE_INVENTORY_FAILURE = 'CREATE_INVENTORY_FAILURE';

export const DELETE_INVENTORY_SUCCESS = 'DELETE_INVENTORY_SUCCESS';
export const DELETE_INVENTORY_FAILURE = 'DELETE_INVENTORY_FAILURE';

export const UPDATE_INVENTORY_SUCCESS = 'UPDATE_INVENTORY_SUCCESS';
export const UPDATE_INVENTORY_FAILURE = 'UPDATE_INVENTORY_FAILURE';

export const FETCH_OEM_SPECS_SUCCESS = 'FETCH_OEM_SPECS_SUCCESS';
export const FETCH_OEM_SPECS_FAILURE = 'FETCH_OEM_SPECS_FAILURE';

export const FETCH_OEM_SPEC_SUCCESS = 'FETCH_OEM_SPEC_SUCCESS';
export const FETCH_OEM_SPEC_FAILURE = 'FETCH_OEM_SPEC_FAILURE';

export const CREATE_OEM_SPECS_SUCCESS = 'CREATE_OEM_SPECS_SUCCESS';
export const CREATE_OEM_SPECS_FAILURE = 'CREATE_OEM_SPECS_FAILURE';

